# -*- coding: utf-8 -*-
"""aula_3_2022_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12YYZEwUaF0O89CF4z7EUOpUAUtPXY3yt

A fórmula para calcular a área de uma circunferência é: area = π . raio2. Considerando para este problema que π = 3.14159:

- Efetue o cálculo da área, elevando o valor de raio ao quadrado e multiplicando por π.

Entrada
A entrada contém um valor de ponto flutuante (dupla precisão), no caso, a variável raio.

Saída
Apresentar a mensagem "A=" seguido pelo valor da variável area, conforme exemplo abaixo, com 4 casas após o ponto decimal. Utilize variáveis de dupla precisão (double). Como todos os problemas, não esqueça de imprimir o fim de linha após o resultado, caso contrário, você receberá "Presentation Error".
"""

raio = float(input('Entre com o raio: '))
p = 3.14159

a = p * raio**2
# print('%d' % a)
print(f'{a:.4f}')

a = int(input('Entre com o valor de A: '))
b = int(input('Entre com o valor de B: '))
soma = a + b
print(soma)

def entre_zero_dez(nota):
  while True:
    valor = float(input(f"entre com a nota {nota}: "))
    if valor < 0 or valor > 10:
      print('Valores entre 0 e 10')
      continue
    else:
      return valor

# while True:
#   nota2 = float(input("entre com a nota 2: "))
#   if nota2 < 0 or nota2 > 10:
#     print('Valores entre 0 e 10')
#     continue
#   else:
#     break

nota1 = entre_zero_dez(1)
nota2 = entre_zero_dez(2)

media = ((nota1 * 3.5) + (nota2 * 7.5))/11

print(f'MEDIA = {media:.5f}')

a = 1
if a == 2:
  pass

lst = [8]
lst[0] = 3
#lst.append([1,2,3])
lst.extend([1,2,3])
print(lst.index(3))
lst.insert(1, 5)
lst.pop(0)
lst.remove(1)
print(lst)
lst.reverse()
lst.sort()
lst

tpl = (4,9,2,7)
tpl[1]

a = {'nome': 'andre'}
a = {0: 'andre', 1:'joao', 2:'pedro'}
a[0] = 'ugb'
#del(a[0])
#a.clear()
#b = a.copy()
b = a
b[0] = 'carro'
a[0] = 'jetta'
print(b, a)
print(b.items(), b.keys(), b.values())

lst = [1,3,5,6,8,1,8]
cjt = set(lst)
cjt

# triangulo
a = 3
b = 3
c = 3

if a == b and a == c:
  print('equilátero')
elif a == b or a == c or b == c:
  print('isósceles')
else:
  print('escaleno')

peso = float(input('Entre com o peso: '))
altura = float(input('Entre com a altura: '))

imc = peso/(altura**2)

if imc <= 18.5:
  print('abaixo do peso')
elif imc >= 18.6 and imc <= 24.9:
  print('peso ideal')
elif imc >= 25.0 and imc <= 29.9:
  print('levemente acima do peso')
elif imc >= 30 and imc <= 34.9:
  print('obesidade grau I')
elif imc >= 35 and imc <= 39.9:
  print('obesidade grau II (severo)')
else:
  print('obesidade grau III (mórbido)')

"""#2. Construir um algoritmo para calcular a média de um conjunto de valores inteiros e positivos."""

valores = [3, 9, 6, 8]
soma = valores[0] + valores[1] + valores[2]
media = soma/3
print(media)

valores = []
while True:
  valor = int(input("entre com um valor: "))
  if valor == -1:
    break
  valores.append(valor)
#valores = [3, 9, 6, 8, 10]
print(valores)
media = sum(valores)/len(valores)
# soma = 0
# contador = 0
# for valor in valores:
#   soma = soma + valor
#   contador = contador + 1
# media = soma/len(valores)
print(media)